services:
  - type: web
    name: discord-link-hunter
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 2 --threads 2 --timeout 120 --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TURSO_URL
        sync: false
      - key: TURSO_TOKEN
        sync: false
      - key: REDDIT_CLIENT_ID
        sync: false
      - key: REDDIT_CLIENT_SECRET
        sync: false
      - key: WEBSHARE_USER
        sync: false
      - key: WEBSHARE_PASS
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
